name: Advanced CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: shencko/kub-repo:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker pull shencko/kub-repo:${{ github.sha }}
          docker run shencko/kub-repo:${{ github.sha }} /usr/src/app/run-tests.sh

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Deploy to Staging
        run: |
          kubectl apply -f k8s/staging.yml
          kubectl rollout status deployment/myapp-deployment

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Deploy to Production
        run: |
          kubectl apply -f k8s/production.yml
          kubectl rollout status deployment/myapp-deployment
